<?php 
return array (
  'RUNTIEM_URL' => 'http://www.daogoge.com/recept.php?url',
  'template_name' => 'default',
  'style_name' => 'default',
  'waptemplate_name' => 'default',
  'wapstyle_name' => 'default',
  'stay_money' => 0.05,
  'stay_percent' => '0.05',
  'permit_days' => '7',
  'msg_uid' => 'j19920118',
  'msg_pwd' => '51fenqi',
  'msg_url' => 'http://service.winic.org/sys_port/gateway/?',
  'msg_format' => '你好！您的订单号为：%s的分期订单已经超出还款日，一共产生滞纳金 %s元，请尽快到公司官方网站进行还款操作。',
  'site_name' => '51分期',
  'site_title' => '51分期',
  'site_description' => '51分期商城,零首付，超值套餐',
  'site_keywords' => '51分期商城',
  'icp_number' => '',
  'site_region' => '',
  'site_address' => '',
  'site_postcode' => '',
  'site_phone_tel' => '',
  'site_email' => '',
  'site_status' => '1',
  'closed_reason' => '商城维护中，暂时关闭，请稍候访问。',
  'hot_search' => '',
  'site_logo' => 'data/files/mall/settings/site_logo.png',
  'default_user_img' => 'data/files/mall/settings/default_user_img.jpg',
  'interval_time' => 0.2,
  'pb_months' => '1',
  'card_img' => 'data/files/mall/settings/card_img.png',
  'userphoto' => 'data/files/mall/settings/userphoto.jpg',
  'school_card' => 'data/files/mall/settings/school_card.png',
  'study_credit_img' => 'data/files/mall/settings/study_credit_img.png',
  'guarantee_school_card' => 'data/files/mall/settings/school_card.png',
  'guarantee_card' => 'data/files/mall/settings/card_img.png',
  'guarantee_photo' => 'data/files/mall/settings/userphoto.jpg',
  'lunbotu' => '{"1":{"url":"data\\/files\\/pic_slides_wap\\/pic_slides_wap_1.jpg","link":"index.php"},"2":{"url":"data\\/files\\/pic_slides_wap\\/pic_slides_wap_2.jpg","link":"index.php"},"3":{"url":"data\\/files\\/pic_slides_wap\\/pic_slides_wap_3.jpg","link":"index.php"}}',
  'search_right' => 
  array (
    'url' => 'data/files/top_aside_imgs/search_right.png',
    'link' => 'index.php',
  ),
  'copyright' => '',
  'service' => 'http://wpd.b.qq.com/page/webchat.html?nameAccount=4006008076',
  'service_key' => ' 
				 
	<!-- WPA Button Begin -->
<script charset="utf-8" type="text/javascript" src="http://wpa.b.qq.com/cgi/wpa.php?key=XzkzODAyODIyM18xODU4NzNfNDAwNjAwODA3Nl8"></script>
<!-- WPA Button END -->
<!-- WPA Button Begin -->
<script charset="utf-8" type="text/javascript" src="http://wpa.b.qq.com/cgi/wpa.php?key=XzkzODAyODIyM18xODU5NjlfNDAwNjAwODA3Nl8"></script>
<!-- WPA Button End -->				
				
			',
  'lunbo_right' => 
  array (
    'url' => '',
    'link' => '',
  ),
  'top_broadcast' => 
  array (
    'url' => '',
    'link' => '',
  ),
  'email_type' => '1',
  'email_host' => 'smtp.163.com',
  'email_port' => '25',
  'email_addr' => '13244550508@163.com',
  'email_id' => '13244550508@163.com',
  'email_pass' => 'hkfggbcdoagswmte',
  'email_test' => '784139247@qq.com',
  'kefus' => 
  array (
    'kefu1_qq' => '784139247',
    'kefu1_tel' => '13244550508',
    'kefu2_qq' => '784139247',
    'kefu2_tel' => '13244550508',
    'kefu3_qq' => '',
    'kefu3_tel' => '',
    'kefu4_qq' => '',
    'kefu4_tel' => '',
    'kefu5_qq' => '',
    'kefu5_tel' => '',
    'kefu6_qq' => '',
    'kefu6_tel' => '',
    'kefu7_qq' => '',
    'kefu7_tel' => '',
  ),
  'charges_reg_per' => '1',
  'charges_reg_pct' => '3',
  'withdraw_line' => '100',
  '1_charges_reg_per' => '1',
  '1_charges_unsigned_pct' => '10',
  '1_charges_signed_pct' => '3',
  '1_withdraw_line' => '4',
  '2_charges_reg_per' => '5',
  '2_charges_unsigned_pct' => '5',
  '2_charges_signed_pct' => '7',
  '2_withdraw_line' => '8',
  '3_charges_reg_per' => '9',
  '3_charges_unsigned_pct' => '2',
  '3_charges_signed_pct' => '3',
  '3_withdraw_line' => '2',
  '4_charges_reg_per' => '1',
  '4_charges_unsigned_pct' => '1',
  '4_charges_signed_pct' => '4',
  '4_withdraw_line' => '4',
  '5_charges_reg_per' => '2',
  '5_charges_unsigned_pct' => '0.5',
  '5_charges_signed_pct' => '5',
  '5_withdraw_line' => '2',
);
?>